- name: Close Stale Issues
  uses: actions/stale@1.0.0
  with:
    # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # The message to post on the issue when tagging it. If none provided, will not mark iusses stale.
    stale-issue-message: # optional
    # The message to post on the pr when tagging it. If none provided, will not mark prs stale.
    stale-pr-message: # optional
    # The number of days old an issue can be before marking it stale
    days-before-stale: # optional, default is 60
    # The number of days to wait to close an issue or pr after it being marked stale
    days-before-close: # optional, default is 7
    # The label to apply when an issue is stale
    stale-issue-label: # optional, default is Stale
    # The label to apply when a pr is stale
    stale-pr-label: # optional, default is Stale
    # The maximum number of operations per run, used to control rate limiting
    operations-per-run: # optional, default is 30
